config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  resources :bookings do
    member do
      # /booking/1/charge
      post 'charge' 
    end
  end

  resources :photos
  resources :locations
  resources :profiles
  resources :tours
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get '/profile', to: 'profiles#show'
  get '/mytours', to: 'tours#mytours', as: :mytours
  get '/mybookings', to: 'bookings#mybookings', as: :mybookings
  get '/contact', to: 'pages#contact'
  post '/contact', to: 'pages#contact_email'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :user_id, uniqueness: { message: 'can only have one profile.' }

  def fullname
    "#{first_name} #{last_name}"
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy, :view]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @profile.user = current_user
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :view, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    @profile = current_user.profile

    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :view, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :about_me, :intro_tour_guide, :street_address, :city, :state, :country_code, :postcode, :phone_number, :is_tour_guide, :is_photographer, :has_car, :has_historical_knowledge)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if @profile.user.photos.where(is_profile: true).count == 0 %>
    <%= link_to 'Create profile photo', new_photo_path(@photo) %>
<% end %>

<% @profile.user.photos.each do |photo| %>
  <% if photo.is_profile %>
      <%= image_tag photo.image_url(:medium) %>
      <% if policy(photo).edit? %>
          <%= link_to 'Edit', edit_photo_path(photo) %>
      <% end %>
  <% end %>
<% end %> 

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :profile_first_name, required: true %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :profile_last_name, required: true %>
  </div>
  

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address, id: :profile_street_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :profile_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :profile_state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.country_select :country_code, priority_countries: ['AU', 'NZ'], id: :profile_country_code %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.text_field :postcode, id: :profile_postcode %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :profile_phone_number %>
  </div>



    <div class="field">
    <%= form.label :about_me %>
    <%= form.text_area :about_me, id: :profile_about_me %>
  </div>



  <div class="field">
    <%= form.check_box :is_tour_guide, id: :profile_is_tour_guide %>
    <%= form.label :i_am_a_tour_guide %>
  </div>

  <div class="field">
    <%= form.check_box :is_photographer, id: :profile_is_photographer %>
    <%= form.label :i_take_photo %>
  </div>

  <div class="field">
    <%= form.check_box :has_car, id: :profile_has_car %>
    <%= form.label :i_drive %>
  </div>

  <div class="field">
    <%= form.check_box :has_historical_knowledge, id: :profile_has_historical_knowledge %>
    <%= form.label :i_have_historical_knowledge_for_tours %>
    
  </div>
  
  <div class="field">
    <%= form.label "About me as a tour guide" %>
    <%= form.text_area :intro_tour_guide, id: :profile_intro_tour_guide %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>My Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'View', @profile, class: "right" %>

app/views/profiles/index.html.erb
<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Street address</th>
      <th>City</th>
      <th>State</th>
      <th>Country code</th>
      <th>Postcode</th>
      <th>Phone number</th>
      <th>About me</th>

      <th>Is tour guide</th>
      <th>Is photographer</th>
      <th>Has car</th>
      <th>Has historical knowledge</th>
      <th>Intro tour guide</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
 
      <tr>
      <td><%= profile.id %></td>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.street_address %></td>
        <td><%= profile.city %></td>
        <td><%= profile.state %></td>
        <td><%= profile.country_code %></td>
        <td><%= profile.postcode %></td>
        <td><%= profile.phone_number %></td>
        <td><%= profile.about_me %></td>

        <td><%= profile.is_tour_guide %></td>
        <td><%= profile.is_photographer %></td>
        <td><%= profile.has_car %></td>
        <td><%= profile.has_historical_knowledge %></td>
        <td><%= profile.intro_tour_guide %></td>
        <td><%= profile.user.email %></td>
        <td><%= link_to 'Show', profile %></td>
        <% if policy(profile).edit? %>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <% end %>
        <% if policy(profile).destroy? %>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<h1>Profile</h1>

<div class="flex-container">
<div class="flex-item profile-box">
 
<% if @profile.user == current_user %>
  <% if @profile.user.photos.where(is_profile: true).count == 0 %>
      <%= link_to 'Create profile photo', new_photo_path(@photo), class: "right" %>
  <% end %>
<% end %>

<% @profile.user.photos.each do |photo| %>
  <% if photo.is_profile %>
      <%= image_tag photo.image_url(:medium) %>
      <% if policy(photo).edit? %>
          <%= link_to 'Edit', edit_photo_path(photo), class: "right" %>
      <% end %>
  <% end %>
<% end %> 


<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>About me:</strong>
  <%= @profile.about_me %>
</p>

<% if @profile.is_tour_guide %>
  <p>
    <strong>About me as a tour guide:</strong>
    <%= @profile.intro_tour_guide %>
  </p>
<% end %>

<% if @profile.user != current_user %>
<%= link_to 'Contact Me', contact_path(user: @profile.user) %>
<% end %>

<% if policy(@profile).edit? %>
<p>
  <strong>Street address:</strong>
  <%= @profile.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @profile.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @profile.state %>
</p>

<p>
  <strong>Country code:</strong>
  <%= @profile.country_code %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @profile.postcode %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @profile.phone_number %>
</p>

<p>
  <strong>Tour guide:</strong>
  <%= @profile.is_tour_guide %>
</p>

<p>
  <strong>Photographer:</strong>
  <%= @profile.is_photographer %>
</p>

<p>
  <strong>Driving:</strong>
  <%= @profile.has_car %>
</p>

<p>
  <strong>Historical knowledge:</strong>
  <%= @profile.has_historical_knowledge %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile), class: "right" %>
<% end %>

</div>
</div>