config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  resources :bookings do
    member do
      # /booking/1/charge
      post 'charge' 
    end
  end

  resources :photos
  resources :locations
  resources :profiles
  resources :tours
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get '/profile', to: 'profiles#show'
  get '/mytours', to: 'tours#mytours', as: :mytours
  get '/mybookings', to: 'bookings#mybookings', as: :mybookings
  get '/contact', to: 'pages#contact'
  post '/contact', to: 'pages#contact_email'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord

  belongs_to :traveller, class_name: "User"
  belongs_to :tour_guide, class_name: "User"
  belongs_to :tour


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:charge, :show, :edit, :update, :destroy]
  after_action :set_paid, only:[:charge]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  def mybookings
    @my_paid_bookings = current_user.bookings_as_traveller.all.where(has_paid: true).order(created_at: 'ASC')
    @my_unpaid_bookings = current_user.bookings_as_traveller.all.where(has_paid: false).order(created_at: 'ASC')
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @traveller = params[:traveller_id]
    @tour_guide = params[:tour_guide_id]
    @tour= params[:tour_id]
  end

  # GET /bookings/1/edit
  def edit
    @traveller = @booking.traveller_id
    @tour_guide = @booking.tour_guide_id
    @tour= @booking.tour_id
    
  end

  # POST / sneakers/1/charge
  def charge

    if current_user.stripe_id.blank?
        customer = Stripe::Customer.create(
          email: params[:stripeEmail],
          source: params[:stripeToken]
        )
        current_user.stripe_id = customer.id 
        current_user.save! 
    end

      charge = Stripe::Charge.create(
        customer: current_user.stripe_id,
        amount: @booking.tour.price_in_cents.to_i,
        description: "Tour: #{@booking.tour.location.name}",
        currency:'AUD',
        receipt_email: current_user.email, # Will not send with test API keys
      ) 

      flash[:notice] = 'Payment made!'
      redirect_back fallback_location: mytours_path
    
      rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to charge_booking_path
  end


  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    @traveller = @booking.traveller_id
    @tour_guide = @booking.tour_guide_id
    @tour= @booking.tour_id
    
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:tour_guide_id, :traveller_id,:tour_id, :has_paid, :rating, :review)
    end  

    def set_paid
      Booking.where(traveller_id: current_user.id, id: @booking.id).update(has_paid: true)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_charge_form.html.erb
<%= form_tag charge_booking_path(booking) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

    <p>  
        <label class="amount">
          <span><strong>Price:</strong> <%= number_to_currency booking.tour.price %></span>
        </label>
    </p>
    
  </article>


  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description=<%= booking.tour.location.name %>
          data-amount=<%= booking.tour.price_in_cents.to_i %>
          data-currency="AUD"
          data-email=<%= user.email %>
          data-locale="auto"></script>
<% end %>

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<% if booking.has_paid %>
  <%= form.hidden_field :tour_guide_id, value: booking.tour_guide_id %>
  <%= form.hidden_field :traveller_id, value: booking.traveller_id %>
  <%= form.hidden_field :tour_id, value: booking.tour_id %>
<% else %>
  <%= form.hidden_field :tour_guide_id, value: @tour_guide %>
  <%= form.hidden_field :traveller_id, value: @traveller %>
  <%= form.hidden_field :tour_id, value: @tour %>
<% end %>

<% if booking.tour_guide_id == current_user.id %>
  <div class="field">
    <%= form.label :has_paid %>
    <%= form.check_box :has_paid, id: :booking_has_paid %>
  </div>
<% end %>

<% if booking.has_paid && booking.traveller_id == current_user.id %>
  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, step: 0.5, max: 10, id: :booking_rating %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review, id: :booking_review %>
  </div>
<% end %>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/_my_paid_bookings.html.erb
<div class="flex-container">
<% my_paid_bookings.each do |paidbooking| %>
    <div class="flex-item">
        Tour Guide: <%= link_to "#{paidbooking.tour_guide.profile.fullname}", profile_path(paidbooking.tour_guide.profile) %>
        <br>
        <%= paidbooking.tour.location.name %>
        <br>
        <%= paidbooking.tour.start_date_time %>
        <br>
        <%= paidbooking.tour.end_date_time %>
        <br>
        <%= paidbooking.tour.description %>
        <br>
        <%= paidbooking.has_paid ? "Paid" : "Unpaid" %>
        <br>
       AUD <%= number_to_currency paidbooking.tour.price %>
       <br>
        <%= link_to 'View', booking_path(paidbooking) %> | 
        <%= link_to 'Review', edit_booking_path(paidbooking) %>
    </div>

    
<% end %>
</div>

app/views/bookings/_my_unpaid_bookings.html.erb
<div class="flex-container">
<% my_unpaid_bookings.each do |booking| %>
    <div class="flex-item">
    Tour Guide: <%= link_to "#{booking.tour_guide.profile.fullname}", profile_path(booking.tour_guide.profile) %>
        <br>
        <%= booking.tour.location.name %>
        <br>
        <%= booking.tour.start_date_time %>
        <br>
        <%= booking.tour.end_date_time %>
        <br>
        <%= booking.tour.description %>
        <br>
       AUD <%= number_to_currency booking.tour.price %>
        <br>
        <%= link_to 'View', booking_path(booking) %>
        <%= link_to 'Pay now', booking, class: "button right" %>
    </div>
<% end %>
</div>

app/views/bookings/edit.html.erb
<div class="flex-container">
<div class="flex-item">
<% if @booking.has_paid && @booking.traveller_id == current_user.id %>
    <h2>Review</h2>
<% else %>
    <h2>Editing Booking</h2>
<% end %>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
</div>
</div>

app/views/bookings/index.html.erb
<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Traveller</th>
      <th>Tour guide</th>
      <th>Tour</th>
      <th>Has paid</th>
      <th>Rating</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.traveller.email %></td>
        <td><%= booking.tour_guide.email %></td>
        <td><%= booking.tour.location.name %></td>
        <td><%= booking.has_paid %></td>
        <td><%= booking.rating %></td>
        <td><%= booking.review %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/mybookings.html.erb
<h1>My Tours - As Traveller</h1>

<%= link_to "As Tour Guide", mytours_path %> | <span class="blue">As Traveller</span>

<br><br>

<h2>Unpaid Booked Tours</h2>
<% if @my_unpaid_bookings.present? %>

        <%= render 'my_unpaid_bookings', my_unpaid_bookings: @my_unpaid_bookings %>

<% else %>
    <p>You don't have any unpaid tours to travel yet.</p>
<% end %>

<h2>Paid Booked Tours</h2>
<% if @my_paid_bookings.present? %>

        <%= render 'my_paid_bookings', my_paid_bookings: @my_paid_bookings %>

<% else %>
    <p>You don't have any paid tours to travel yet.</p>
<% end %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>
<p>Confirm booking? </p>
<%= render 'form', booking: @booking %>

app/views/bookings/show.html.erb
<div class="flex-container">
<div class="flex-item">

<h2>Booking</h2>

<p>
  <strong>Traveller:</strong>
  <%= @booking.traveller.profile.fullname %>
</p>

<p>
  <strong>Tour guide:</strong>
  <%= @booking.tour_guide.profile.fullname %>
</p>

<p>
  <strong>Tour:</strong>
  <%= @booking.tour.location.name %>
</p>

<p>
  <strong>From:</strong>
  <%= @booking.tour.start_date_time %>
</p>

<p>
  <strong>To:</strong>
  <%= @booking.tour.end_date_time %>
</p>

<p>
  <strong>Payment status:</strong>
  <%= @booking.has_paid ? "Paid" : "Unpaid" %>
</p>


<% if @booking.traveller_id == current_user.id %>
  <% unless @booking.has_paid %>
        <%= render 'charge_form', booking: @booking, user: current_user %>
  <% else %>
    <p>
      <strong>Rating:</strong>
      <%= @booking.rating %>
    </p>
    <p>
      <strong>Review:</strong>
      <%= @booking.review %>
    </p>
    <br>
    <%= link_to 'Review', edit_booking_path(@booking) %>
  <% end %>  

  <% elsif @booking.tour_guide_id == current_user.id %>
      <%= link_to 'Edit Payment Status', edit_booking_path(@booking) %>
      
<% end %>

</div>
</div>