config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  resources :bookings do
    member do
      # /booking/1/charge
      post 'charge' 
    end
  end

  resources :photos
  resources :locations
  resources :profiles
  resources :tours
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get '/profile', to: 'profiles#show'
  get '/mytours', to: 'tours#mytours', as: :mytours
  get '/mybookings', to: 'bookings#mybookings', as: :mybookings
  get '/contact', to: 'pages#contact'
  post '/contact', to: 'pages#contact_email'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :user
  belongs_to :location

  def price_in_cents
    price * 100.00
  end

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]
  before_action :set_booked, only: [:mytours]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
    authorize @tours
  end

  def mytours
    @mytours = current_user.tours.all.where(has_booked: false).order(start_date_time: 'ASC')
    @mybookedtours = current_user.bookings_as_tour_guide.all.order(created_at: 'ASC')
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
    @tours = current_user.tours
  end

  # GET /tours/new
  def new
    @tour = Tour.new
    @tour.user = current_user
    @locations = Location.all
    authorize @tour
  end

  # GET /tours/1/edit
  def edit
    @tour.user = current_user
    @locations = Location.all
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)
    @tour.user = current_user
    @locations = Location.all
    authorize @tour

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
      authorize @tour
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:start_date_time, :end_date_time, :description, :price, :location_id)
    end

    def set_booked
      @bookings = Booking.all
      @tours = Tour.all
      @bookings.each do |booking|
        @tours.each do |tour|
          if booking.tour_id == tour.id
            Tour.where(id: tour.id).update(has_booked: true)
          end
        end
      end
    end

end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_with(model: tour, local: true) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <strong>Tour Guide:</strong>
    <%= tour.user.profile.fullname %>
</p>

<div class="field">
    <%= form.label :location %> 
    <%= form.collection_select :location_id, locations, :id, :name, {selected: tour.location_id}, prompt: true, required: true %>
  <br> 
   <%= link_to 'Create new location', new_location_path(@location) %>
  </div>

  <div class="field">
    <%= form.label :start_date_time %>
    <%= form.datetime_select :start_date_time, id: :tour_start_date_time %>
  </div>

  <div class="field">
    <%= form.label :end_date_time %>
    <%= form.datetime_select :end_date_time, id: :tour_end_date_time %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :tour_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.5, id: :tour_price %>
  </div>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tours/_mybookedtours.html.erb
<div class="flex-container">

<% mybookedtours.each do |bookedtour| %>
    <div class="flex-item">
        Traveller: <%= link_to "#{bookedtour.traveller.profile.fullname}", profile_path(bookedtour.traveller.profile) %>
        <br>
        <%= bookedtour.tour.location.name %>
        <br>
        <%= bookedtour.tour.start_date_time %>
        <br>
        <%= bookedtour.tour.end_date_time %>
        <br>
        <%= bookedtour.has_paid ? "Paid" : "Unpaid" %>
        <br>
       AUD <%= number_to_currency bookedtour.tour.price %>
        <br>
        <%= link_to 'View', booking_path(bookedtour) %> | 
        <%= link_to 'Delete', bookedtour, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
    
<% end %>

</div>

app/views/tours/_mytours.html.erb
<div class="flex-container">


<% mytours.each do |tour| %>
    <div class="flex-item">
        <%= tour.location.name %>
        <br>
        <%= tour.start_date_time %>
        <br>
        <%= tour.end_date_time %>
        <br>
        <%= tour.description %>
        <br>
       AUD <%= number_to_currency tour.price %>
        <br>
    <% if policy(tour).edit? %>
        <%= link_to 'Edit', edit_tour_path(tour) %> | 
    <% end %>

    <% if policy(tour).destroy? %>
        <%= link_to 'Delete', tour, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    </div>
    
<% end %>
</div>

app/views/tours/_tour.html.erb
<h3><%= tour.location.name %></h3><br>

<% tour.user.photos.each do |photo| %>
  <% if photo.is_profile %>
      <%= image_tag photo.image_url(:thumb), class: "thumb" %>
  <% end %>
<% end %> 

<strong>Tour Guide:</strong> <%= tour.user.profile.first_name %><br>
<strong>From:</strong> <%= tour.start_date_time %><br>
<strong>To:</strong> <%= tour.end_date_time %><br>
<strong>Tour:</strong> <%= tour.description %><br>
<strong>Price:</strong> AUD <%= number_to_currency tour.price %><br>


    <% if user_signed_in? %>
            <% if tour.user_id != current_user.id %>
                <%= link_to 'Book', new_booking_path(tour_guide_id: tour.user_id, traveller_id: current_user.id, tour_id: tour.id), class: "button right" %>
            <% end %>
    <% end %>

<div class="right">
    <% if policy(tour).edit? %>
        <br>
        <%= link_to 'Edit', edit_tour_path(tour) %> | 
    <% end %>
    
    <% if policy(tour).destroy? %>
        <%= link_to 'Delete', tour, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
</div>

app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form', tour: @tour, locations: @locations %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<h1>Tours</h1>

<p>
<%= link_to 'Add Tour', new_tour_path %>
</p>


<% @tours.each do |tour| %>
    <div style="border: 1px; padding: 10px;">
      <%= link_to tour_path(tour) do %>
          <%= render 'tour', tour: tour %>
      <% end %>
    </div>
<% end %>

app/views/tours/mytours.html.erb
<h1>My Tours - As Tour Guide</h1>

<span class="blue">As Tour Guide</span> | <%= link_to "As Traveller", mybookings_path %>

<br><br>
<%= link_to 'Add Tour', new_tour_path, class: "button" %>


<h2>Booked Tours</h2>

<% if @mybookedtours.present? %>
    <%= render 'mybookedtours', mybookedtours: @mybookedtours %>
<% else %>
    <p>You don't have any tours booked yet.</p>
<% end %>

<h2>Unbooked Tours</h2>
<% if @mytours.present? %>
    <%= render 'mytours', mytours: @mytours %>
<% else %>
    <p>You don't have any tours unbooked/created yet.</p>
<% end %>

app/views/tours/new.html.erb
<h1>New Tour</h1>

<%= render 'form', tour: @tour, locations: @locations %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<div class="flex-container">
<div class="flex-item">
<% @tour.user.photos.each do |photo| %>
  <% if photo.is_profile %>
      <%= image_tag photo.image_url(:medium) %>
  <% end %>
<% end %> 

<p>
  <strong>Tour Guide:</strong>
  <%= link_to @tour.user.profile.fullname, profile_path(@tour.user.profile) %>
</p>

<p>
  <strong>Location:</strong>
  <%= @tour.location.name %>
</p>

<p>
  <strong>From:</strong>
  <%= @tour.start_date_time %>
</p>

<p>
  <strong>To:</strong>
  <%= @tour.end_date_time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tour.description %>
</p>

<p>
  <strong>Price:</strong>
  AUD <%= number_to_currency @tour.price %>
</p>


<% if user_signed_in? %>

    <% if @tour.user_id != current_user.id %>
        <%= link_to 'Book', new_booking_path(tour_guide_id: @tour.user_id, traveller_id: current_user.id, tour_id: @tour.id), class: "button" %>
    <% end %>


    <% if policy(@tour).edit? %>
        <br>
        <%= link_to 'Edit', edit_tour_path(@tour), class: "right" %> 
    <% end %>

    <% if policy(@tour).destroy? %>
        <%= link_to 'Delete', @tour, method: :delete, data: { confirm: 'Are you sure?' }, class: "right" %>
    <% end %>

<% end %>

<br>
<%= link_to 'Back', :back, class: "left" %>
</div>
</div>